require:
  - rubocop-rails
  - rubocop-rspec

Style/Documentation:
  Enabled: false

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'config/initializers/*'
    - 'bin/*'
    - 'db/**/*'
    - 'node_modules/**/*'
  NewCops: enable
  TargetRubyVersion: 3.0.0

Style/FrozenStringLiteralComment:
  Enabled: false
  EnforcedStyle: always

Rails/FilePath:
  Enabled: false

RSpec/LetSetup:
  Exclude:
    - 'spec/models/user_spec.rb'


RSpec/UnspecifiedException:
  Exclude:


RSpec/MultipleExpectations:
  Max: 9

RSpec/ExampleLength:
  Max: 18

RSpec/FilePath:
  Enabled: false

RSpec/HookArgument:
  Exclude:


RSpec/NestedGroups:
  Max: 5


RSpec/NamedSubject:
  Exclude:
    - 'spec/**/*'

RSpec/MultipleMemoizedHelpers:
  Max: 10

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'
Lint/ImplicitStringConcatenation:
  Exclude:

Style/BlockComments:
  Description: 'Do not use block comments.'
  StyleGuide: '#no-block-comments'
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'spec/**/*'
    - 'config/environments/*'

Metrics/MethodLength:
  Exclude:
    - 'app/helpers/*'


Metrics/ClassLength:
  Exclude:


Metrics/AbcSize:
  Exclude:


Layout/LineLength:
  Max: 120
  Exclude:


Layout/EmptyLineAfterGuardClause:
  Exclude:

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/GuardClause:
  Enabled: false
